In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os
import sys

# 添加项目根目录到路径
# sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from postgres_manager import PostgreSQLManager
from advanced_manager import AdvancedPostgreSQLManager

In [2]:
db = PostgreSQLManager()

2025-09-23 17:00:27 | INFO | 数据库连接成功

In [3]:
hfq_close = pd.read_csv("D:/program_learning/光大实习/raw_data/hfq/close.csv",index_col='date')

In [ ]:
c = hfq_close.iloc[:,:]

In [11]:
c

,600000.SH,600004.SH,600006.SH,600007.SH,600008.SH,600009.SH,600010.SH,600011.SH,600012.SH,600015.SH,...,600121.SH,600123.SH,600125.SH,600126.SH,600127.SH,600128.SH,600129.SH,600130.SH,600131.SH,600132.SH
date,,,,,,,,,,,,,,,,,,,,,
2015-01-05,96.671576,16.021395,16.326623,20.396198,32.716495,49.796891,22.123511,28.356944,9.668132,28.111261,...,18.443832,60.996347,112.564651,17.680324,24.025169,26.395816,38.002802,21.806100,25.809134,64.856336
2015-01-06,97.032515,16.076404,16.588268,19.671460,35.990851,48.729641,21.561482,27.538955,10.201862,27.612981,...,17.737848,58.196867,117.394158,17.680324,24.183229,27.039093,38.002802,22.155697,25.656868,65.170790
2015-01-07,95.107506,15.911376,16.248130,19.658518,34.529568,48.947942,21.919137,27.508659,9.896874,27.280795,...,17.855512,57.873851,114.917488,17.680324,24.183229,27.618043,38.002802,21.937199,26.265933,65.524552
2015-01-08,91.738739,15.567570,15.724840,19.179673,34.231899,48.511340,21.561482,26.236232,9.622384,26.263475,...,17.708432,56.581783,111.573983,17.680324,24.143714,27.167749,38.002802,22.505294,25.733001,65.170790
2015-01-09,92.821557,15.636331,15.515525,18.985547,33.095346,48.390062,21.357108,25.933273,9.561386,26.657946,...,17.355440,55.774241,109.221147,17.680324,23.590503,26.867553,38.002802,22.286796,25.276202,65.563859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-05-27,108.702886,25.758002,29.199537,23.411626,46.409255,81.256495,36.480802,36.627719,23.041874,33.758427,...,29.416000,66.541469,187.360085,39.209229,40.423927,48.138592,88.941776,65.156104,43.472023,112.850024
2015-05-28,102.506761,23.722666,26.269118,22.026858,41.781860,74.125328,33.210814,33.416356,23.209617,31.350076,...,28.062864,63.203628,170.180236,35.534268,36.432904,45.093746,80.056551,58.644863,39.132434,101.608259
2015-05-29,102.506761,23.846436,25.353362,21.988033,40.212334,72.742754,32.444411,32.780142,23.911091,31.183983,...,27.356880,63.688154,167.316925,36.199812,36.116783,44.021617,81.757501,59.431456,38.371103,101.097270
2015-06-01,107.860694,26.225579,27.891314,23.295150,42.153238,77.108775,33.772843,36.052097,24.033086,32.803391,...,29.916072,70.040818,180.513052,37.530900,38.053022,46.508956,86.211304,61.834934,41.378362,105.460332
2015-06-02,107.319285,27.504540,28.126794,24.252840,43.738768,77.375587,33.977217,36.536831,23.804345,33.031769,...,30.416144,70.686852,193.958162,38.688368,40.621502,49.210721,89.389394,61.966033,43.167490,109.862702

In [10]:
success = db.insert_data("price_hfq_close",
                        c,update_existing=True)

2025-09-23 17:02:19 | INFO | [Function: insert_data started...]
2025-09-23 17:02:19 | INFO | 直接使用传入的DataFrame，形状: (100, 100)
2025-09-23 17:02:19 | INFO | 数据开始导入表 price_hfq_close
2025-09-23 17:02:19 | INFO | 检测到跨度 148 天的数据，将按日显示导入进度
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-05 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-06 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-07 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-08 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-09 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-12 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-13 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-14 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-15 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-16 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-19 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-20 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-21 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-22 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-23 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-26 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-27 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-28 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-29 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-01-30 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-02 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-03 因子 hfq_close 导入成功，共 98 条记录

table_columns
{'datetime': 'timestamp without time zone', 'code': 'character varying', 'metric': 'character varying', 'value': 'double precision'}

2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-04 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-05 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-06 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-09 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-10 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-11 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-12 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-13 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-16 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-17 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-25 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-26 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-02-27 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-02 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-03 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-04 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-05 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-06 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-09 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-10 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-11 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-12 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-13 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-16 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-17 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-18 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-19 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-20 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-23 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-24 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-25 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-26 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-27 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-30 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-03-31 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-01 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-02 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-03 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-07 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-08 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-09 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-10 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-13 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-14 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-15 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-16 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-17 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-20 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-21 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-22 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-23 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-24 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-27 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-28 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-29 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-04-30 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-04 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-05 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-06 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-07 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-08 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-11 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-12 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-13 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:19 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-14 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-15 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-18 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-19 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-20 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-21 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-22 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-25 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-26 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-27 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-28 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-05-29 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-06-01 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 当前时间 2025-09-23 17:02:19, 导入时间点 2015-06-02 因子 hfq_close 导入成功，共 98 条记录
2025-09-23 17:02:20 | INFO | 数据成功导入表 price_hfq_close, 共 9800 行, 耗时 1.34 秒
2025-09-23 17:02:20 | INFO | 成功向表 price_hfq_close 插入数据
2025-09-23 17:02:20 | INFO | [Function: insert_data completed, elapsed time: 1.36s]

In [8]:
c.stack()

date
2015-01-05  600000.SH     96.671576
            600004.SH     16.021395
            600006.SH     16.326623
            600007.SH     20.396198
            600008.SH     32.716495
                            ...
2025-03-31  600128.SH     25.816953
            600129.SH     48.712046
            600130.SH     13.721674
            600131.SH     77.255792
            600132.SH    290.129406
Length: 246525, dtype: float64

In [32]:
df = db.query_data("equity_fundamental_data.price_hfq_close", start_date='2016-01-01', end_date='2019-02-01')

2025-09-23 13:30:15 | INFO | [Function: query_data started...]
2025-09-23 13:30:15 | INFO | 执行查询: SELECT * FROM equity_fundamental_data.price_hfq_close WHERE datetime >= %s AND datetime <= %s ORDER BY datetime
2025-09-23 13:30:15 | INFO | 查询完成，返回数据形状: (754, 500)
2025-09-23 13:30:15 | INFO | [Function: query_data completed, elapsed time: 0.57s]

In [33]:
df

,600000.SH,600004.SH,600006.SH,600007.SH,600008.SH,600009.SH,600010.SH,600011.SH,600012.SH,600015.SH,...,600645.SH,600648.SH,600649.SH,600650.SH,600651.SH,600653.SH,600654.SH,600655.SH,600657.SH,600658.SH
datetime,,,,,,,,,,,,,,,,,,,,,
2016-01-04,112.068213,18.196811,20.919666,22.599994,25.149792,69.387952,16.656501,25.768408,18.841934,29.257577,...,812.780431,110.377588,259.985683,124.717572,80367.949643,53288.836257,43301.352782,2784.833489,72.062808,39.815073
2016-01-05,113.075567,18.336358,20.159427,22.089924,25.286475,70.590643,17.065249,25.705863,18.593195,29.411160,...,786.386946,111.536530,259.985683,128.515014,75102.880653,53181.182042,43301.352782,2903.457228,72.632925,38.611435
2016-01-06,113.957003,18.741041,20.657515,22.299184,25.696526,72.406954,18.495869,26.268766,18.904118,29.462354,...,824.032391,112.370968,259.985683,127.139562,79157.588956,55011.303691,43301.352782,2907.223061,74.457300,39.593350
2016-01-07,110.242382,17.331626,18.612735,20.075805,23.154210,68.700699,16.707594,24.361153,17.023034,27.465774,...,741.656934,101.430560,233.942213,114.431586,71290.244488,49843.901388,43301.352782,2673.741416,67.729917,35.634015
2016-01-08,110.116463,17.722355,18.691381,20.088883,24.247680,68.798878,18.138214,24.955327,17.100765,27.721746,...,790.137599,102.033210,210.592894,110.424836,69777.293629,51458.714607,43301.352782,2705.750996,69.440269,35.095545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-01-28,98.832054,23.950289,10.164870,18.289706,19.560245,124.464073,10.708160,23.878465,9.535220,24.771495,...,227.400712,65.411822,64.014940,31.029092,20301.732167,22607.385079,2834.612428,1530.286347,51.244853,23.792550
2019-01-29,100.349628,23.671048,9.844717,18.070175,19.274277,125.278895,10.636772,24.018927,9.435025,24.903610,...,226.983973,64.314468,62.142473,30.340252,19991.308128,21961.459791,2744.146074,1540.083315,52.705513,23.084438
2019-01-30,99.590841,24.293970,9.657961,18.097616,19.159889,125.049726,10.565384,22.719657,9.301432,24.804524,...,223.788972,63.551092,63.078706,29.682724,19680.884088,21746.151361,2759.223799,1510.692412,51.366574,22.990023
2019-01-31,101.772355,25.367974,9.684640,18.221103,18.988308,125.533527,10.493996,22.544080,9.301432,25.002696,...,221.149623,63.026271,62.142473,29.087817,17694.170237,23899.235655,2623.524268,1500.895444,51.123131,21.951460
2019-02-01,102.151748,24.916893,9.844717,18.138779,19.388664,126.170106,10.708160,22.649427,9.501822,25.035724,...,229.901147,65.602666,64.248998,29.682724,16452.474080,22930.347723,2593.368817,1567.514824,51.731740,23.084438